"""ContextPlan domain value object.

Represents a retrieval strategy plan generated by the Context Planner.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple

from ria.domain.models.context_request import IntentClassification

__all__ = ["ContextPlan"]


@dataclass(frozen=True)
class ContextPlan:
    """Planned retrieval strategy for building AI context.

    Attributes:
        intent: Classified intent.
        target_symbols: Specific symbols to retrieve.
        target_files: Specific files to retrieve.
        graph_depth: Max depth of graph traversal.
        include_dependencies: True to retrieve dependencies.
        include_references: True to retrieve references.
    """

    intent: IntentClassification
    target_symbols: Tuple[str, ...] = ()
    target_files: Tuple[str, ...] = ()
    graph_depth: int = 2
    include_dependencies: bool = True
    include_references: bool = True

    def __post_init__(self) -> None:
        if self.graph_depth < 0:
            raise ValueError(
                f"graph_depth must be non-negative, got {self.graph_depth}"
            )
